In [3]:
import numpy as np

# Problem 1

# 1D Array

In [61]:
axis0 = np.array([7, 2, 9, 10]) #first row
onedarray = np.array(axis0) #Not a needed function but useful in case 2d array is needed later

print(onedarray)
print(onedarray.shape)
print(onedarray.ndim)

[ 7  2  9 10]
(4,)
1


# 2D Array

In [60]:
axis0 = np.array([5.2, 3.0, 4.5]) #first row
axis1 = np.array([9.1, 0.1, 0.3]) #second row
twodarray = np.array([axis0, axis1]) # combine into full array

print(twodarray)
print(twodarray.shape)
print(twodarray.ndim)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
2


# 3D Array

In [65]:
threedarray = np.array([[[1,4,7], [2,9,7], [1,3,0], [9,6,9]], #main 2D array
                        [[1,2,''], [4,3,''], [7,4,''], ['','','']], #top 2D array
                        [[7,5,''], [0,2,''], [9,8,''], ['','','']]]) # side 2D array


print(threedarray)
print(threedarray.shape)
print(threedarray.ndim)

# The 3D array was trickuy since arrays didn't allow for the different numbered variables however I say that using blank spaces would let the program run and have the desired effect.
# I tried a couple of different ways but was satisfied with this result. If we used matrices instead there is the flexability of the dimensions we want.

[[['1' '4' '7']
  ['2' '9' '7']
  ['1' '3' '0']
  ['9' '6' '9']]

 [['1' '2' '']
  ['4' '3' '']
  ['7' '4' '']
  ['' '' '']]

 [['7' '5' '']
  ['0' '2' '']
  ['9' '8' '']
  ['' '' '']]]
(3, 4, 3)
3


# Problem 2

In [46]:
listy = [x for x in range(1,21)]
print(listy)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Method to remove 10

In [47]:
listy.remove(10) #.remove is used to remove any value or string that is in the numbered position. You could choose to turn everything into a array and filter out a 10 but I didn't think that was what you were asking for.
print(listy)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Method to insert String 'threeve'

In [48]:
listy.insert(0, 'threeve') #.insert is able to insert any string or number into any spot of your choosing. Techically number 1 is in position 0 but .insert shifts the 1 to the 1st position.
print(listy)

['threeve', 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Method to repeat modified listy 3 times

In [49]:
listy = listy * 3 #Everything in the list doesn't classifty as a number you can multiply the list variable by three to show it three times.
print(listy)

['threeve', 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 'threeve', 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 'threeve', 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
oned = matrix